name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
    # perms_list.json ã«å¤‰æ›´ãŒã‚ã£ãŸã¨ãã ã‘èµ·å‹•
    paths:
      - perms_list.json

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # HEAD^ ã¨ã®æ¯”è¼ƒã«å¿…è¦

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Get git diff
        id: git_diff
        run: |
          git diff HEAD^ HEAD -- perms_list.json > diff.txt
          head -c 1900 diff.txt > trimmed_diff.txt

      - name: Notify to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          # diff æ–‡å­—åˆ—ã®å…ˆé ­ã¨æœ«å°¾ã« ```diff ã‚’è¿½åŠ ã—ã¦æ•´å½¢
          echo '```diff' > formatted_diff.txt
          cat trimmed_diff.txt >> formatted_diff.txt
          echo '```' >> formatted_diff.txt

          # ãƒ•ã‚¡ã‚¤ãƒ«ã®å†…å®¹ã‚’èª­ã¿è¾¼ã‚“ã§æ–‡å­—åˆ—å¤‰æ•°ã«ä»£å…¥
          DIFF=$(cat formatted_diff.txt)

          # jqã§æ–‡å­—åˆ—ã¨ã—ã¦æ¸¡ã™
          jq -n \
            --arg content "âœ… perms_list.jsonãŒæ­£å¸¸ã«æ›´æ–°ã•ã‚Œã¾ã—ãŸ
           ðŸ”— https://asukabeehive.github.io/BeeHivePerms/perms_list.json" \
            --arg diff "$DIFF" \
            '{
              username: "GitHub Actions",
              content: $content,
              embeds: [
                {
                  title: "å¤‰æ›´å†…å®¹",
                  description: $diff,
                  color: 65280
                }
              ]
            }' > payload.json

          curl -H "Content-Type: application/json" \
               -X POST \
               -d @payload.json \
               "$DISCORD_WEBHOOK_URL"
